version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Update yarn
          command: sudo npm install --global yarn
      - run:
          name: Update now
          command: sudo npm install -g now
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Install node modules
          command: yarn now-build
      - run:
          name: Install node modules
          command: yarn now-build
      - run:
          name: Export now key
          command: echo $NOW_KEY | base64 --decode --ignore-garbage > ~/.now/auth.json
      - run:
          name: Deploy to now
          command: now
workflows:
  version: 2
  build-web-staging-context:
    jobs:
      - build:
          context: web-staging
          filters:
            branches:
              only:
                - staging
  build-web-master-context:
    jobs:
      - build:
          context: web-master
          filters:
            branches:
              only:
                - master
