version: 2
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Update yarn
          command: sudo npm install --global yarn
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Install node modules
          command: yarn now-build
      - run:
          name: Deploy to now
          command: now
workflows:
  version: 2
  build-web-staging-context:
    jobs:
      - build:
          context: web-staging
          filters:
            branches:
              only:
                - staging
  build-web-master-context:
    jobs:
      - build:
          context: web-master
          filters:
            branches:
              only:
                - master
