version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Update yarn
          command: sudo npm install --global yarn
      - run:
          name: Update now
          command: sudo npm install -g --unsafe-perm now
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Install node modules
          command: yarn now-build
      - run:
          name: Install node modules
          command: yarn now-build
      - run:
          name: Export now key
          command: mkdir ${HOME}/.now && echo $NOW_KEY | base64 --decode --ignore-garbage > ${HOME}/.now/auth.json
      - run:
          name: Set env variables
          command: sed -i "s/@SKYHITZ_ENV/$SKYHITZ_ENV/g" next.config.js && sed -i "s/@FACEBOOK_APP_ID/$FACEBOOK_APP_ID/g" next.config.js && sed -i "s/@STRIPE_PUBLISHABLE_KEY/$STRIPE_PUBLISHABLE_KEY/g" next.config.js
      - run:
          name: Deploy to now
          command: export NOW_JSON="now.$SKYHITZ_ENV.json" && echo $NOW_JSON
      - run:
          name: Deploy to now
          command: now alias -A $NOW_JSON
workflows:
  version: 2
  build-web-staging-context:
    jobs:
      - build:
          context: web-staging
          filters:
            branches:
              only:
                - staging
  build-web-master-context:
    jobs:
      - build:
          context: web-master
          filters:
            branches:
              only:
                - master
